#!/bin/bash

[ -f Makefile ] && ./distclean.sh

TARGET=linux

PREFIX="${HOME}/dani"
DD_HOSTS="p4 anb anb1 render mms box mazsola v3"
PERF_FLAG=""

while [ -n "$1" ]; do
    case "$1" in
	-p)
	    PERF_FLAG="-pg"
	    ;;
	-w)
	    PREFIX=${HOME}/prj/wucsim/inst
	    ;;
	[lLxX]*) TARGET=linux;;
	[mMwW]6*) TARGET=w64;;
	[mMwW]*) TARGET=mingw;;
	*) echo "Unknown target \"${1}\"" >&2; exit 1;;
    esac
    shift
done

export CXXFLAGS="$PERF_FLAG"
export CFLAGS="$PERF_FLAG"


case $TARGET in
    linux|l)
	if echo $DD_HOSTS|grep $(hostname) >/dev/null 2>&1 ; then
	    :
	fi
	./configure --prefix=${PREFIX} \
		    "$@"
	#--enable-ucsim
	;;
    w32)
	export CC=i686-w64-mingw32-gcc
	export CXX=i686-w64-mingw32-g++
	export HOST_OPT='--host=i686-w64-mingw32'
	export LDFLAGS='-static-libgcc -static-libstdc++'
	echo CC=$CC CXX=$CXX HOST=$HOST_OPT
	./configure --prefix=${PREFIX} \
		    $HOST_OPT "$@"
	#--enable-ucsim
	;;
    w64)
	export CC=x86_64-w64-mingw32-gcc
	export CXX=x86_64-w64-mingw32-g++
	export HOST_OPT='--host=x86_64-w64-mingw32'
	export LDFLAGS='-static-libgcc -static-libstdc++'
	echo CC=$CC CXX=$CXX HOST=$HOST_OPT
	./configure --prefix=${PREFIX} \
		    $HOST_OPT "$@"
	#--enable-ucsim
	;;
    *)
	echo >&2 "Do not know how to configure!"
	;;
esac

for d in s51 m6809 stm8 tlcs z80; do
    [ -L ${d}.src/dtest ] || ln -s ../../test/$d ${d}.src/dtest
done

# End of conf
